In [1]:
from pathlib import Path

import xarray as xr

from remake import load_remake

In [2]:
basedir = Path('/gws/nopw/j04/mcs_prime/mmuetz/data/mcs_prime_output/era5_processed/N216grid/')

In [3]:
sorted(basedir.glob('*'))

[PosixPath('/gws/nopw/j04/mcs_prime/mmuetz/data/mcs_prime_output/era5_processed/N216grid/2020-01-01_04:00:00-2020-01-11_03:00:00'),
 PosixPath('/gws/nopw/j04/mcs_prime/mmuetz/data/mcs_prime_output/era5_processed/N216grid/2020-02-01_04:00:00-2020-02-11_03:00:00'),
 PosixPath('/gws/nopw/j04/mcs_prime/mmuetz/data/mcs_prime_output/era5_processed/N216grid/2020-03-01_04:00:00-2020-03-11_03:00:00'),
 PosixPath('/gws/nopw/j04/mcs_prime/mmuetz/data/mcs_prime_output/era5_processed/N216grid/2020-04-01_04:00:00-2020-04-11_03:00:00'),
 PosixPath('/gws/nopw/j04/mcs_prime/mmuetz/data/mcs_prime_output/era5_processed/N216grid/2020-05-01_04:00:00-2020-05-11_03:00:00'),
 PosixPath('/gws/nopw/j04/mcs_prime/mmuetz/data/mcs_prime_output/era5_processed/N216grid/2020-06-01_04:00:00-2020-06-11_03:00:00'),
 PosixPath('/gws/nopw/j04/mcs_prime/mmuetz/data/mcs_prime_output/era5_processed/N216grid/2020-07-01_04:00:00-2020-07-11_03:00:00'),
 PosixPath('/gws/nopw/j04/mcs_prime/mmuetz/data/mcs_prime_output/era5_proces

In [4]:
ds = xr.open_dataset(basedir / '2020-01-01_04:00:00-2020-01-11_03:00:00/ecmwf-era5_oper_an_pl_2020-01-01_04:00:00-2020-01-11_03:00:00.z.nc')

/home/users/mmuetz/miniconda3/envs/upflo_env/lib/python3.12/site-packages/pyproj/network.py:59: UserWarning: pyproj unable to set PROJ database path.
  _set_context_ca_bundle_path(ca_bundle_path)


In [5]:
ds.latitude.values[[0, -1]]

array([-89.72222,  89.72224], dtype=float32)

In [6]:
for m in range(1, 13):
    ds = xr.open_dataset(basedir / f'2020-{m:02d}-01_04:00:00-2020-{m:02d}-11_03:00:00/ecmwf-era5_oper_an_pl_2020-{m:02d}-01_04:00:00-2020-{m:02d}-11_03:00:00.z.nc')    
    print(m, ds.latitude.values[[0, -1]])
    

1 [-89.72222  89.72224]
2 [-89.72222  89.72224]
3 [-89.72222  89.72224]
4 [-89.72222  89.72224]
5 [-89.72222  89.72224]
6 [-89.72222  89.72224]
7 [-89.72222  89.72224]
8 [-89.72222  89.72224]
9 [-89.72222  89.72224]
10 [-89.72222  89.72224]
11 [-89.72222  89.72224]
12 [-89.72222  89.72224]


In [7]:
ds = xr.open_dataset('/gws/nopw/j04/mcs_prime/mmuetz/data/UM_sims/u-di728/share/cycle/20200401T0000Z/engl/um/englaa_pb.merged.20200401T0000Z.u-di728.m01s16i202.500hPa.nc')

In [8]:
ds

<xarray.Dataset> Size: 1GB
Dimensions:              (realization: 10, time: 240, latitude: 324,
                          longitude: 432)
Coordinates:
  * realization          (realization) int32 40B 0 1 2 3 4 5 6 7 8 9
  * time                 (time) datetime64[ns] 2kB 2020-04-01T04:00:00 ... 20...
  * latitude             (latitude) float32 1kB -89.72 -89.17 ... 89.17 89.72
  * longitude            (longitude) float32 2kB 0.4167 1.25 ... 358.7 359.6
    pressure             float32 4B ...
Data variables:
    geopotential_height  (realization, time, latitude, longitude) float32 1GB ...
    latitude_longitude   int32 4B ...
Attributes:
    notes:        removing coords forecast_period and forecast_reference_time
    source:       Data from Met Office Unified Model
    um_version:   13.0
    Conventions:  CF-1.7

In [9]:
ds_bad = xr.open_dataset('/gws/nopw/j04/mcs_prime/mmuetz/data/UM_sims/u-di728/share/cycle/20200401T0000Z/engl/um/englaa_pb.merged.20200401T0000Z.u-di728.m01s16i202.500hPa.nc')

In [10]:
# THIS dataset has NO METADATA! Why?
ds_bad

<xarray.Dataset> Size: 1GB
Dimensions:              (realization: 10, time: 240, latitude: 324,
                          longitude: 432)
Coordinates:
  * realization          (realization) int32 40B 0 1 2 3 4 5 6 7 8 9
  * time                 (time) datetime64[ns] 2kB 2020-04-01T04:00:00 ... 20...
  * latitude             (latitude) float32 1kB -89.72 -89.17 ... 89.17 89.72
  * longitude            (longitude) float32 2kB 0.4167 1.25 ... 358.7 359.6
    pressure             float32 4B ...
Data variables:
    geopotential_height  (realization, time, latitude, longitude) float32 1GB ...
    latitude_longitude   int32 4B ...
Attributes:
    notes:        removing coords forecast_period and forecast_reference_time
    source:       Data from Met Office Unified Model
    um_version:   13.0
    Conventions:  CF-1.7

In [11]:
ds_good = xr.open_dataset('/gws/nopw/j04/mcs_prime/mmuetz/data/UM_sims/u-di728/share/cycle/20200301T0000Z/engl/um/englaa_pb.merged.20200301T0000Z.u-di728.m01s16i202.500hPa.nc')
ds_good

<xarray.Dataset> Size: 1GB
Dimensions:              (realization: 10, time: 240, latitude: 324,
                          longitude: 432)
Coordinates:
  * realization          (realization) int32 40B 0 1 2 3 4 5 6 7 8 9
  * time                 (time) datetime64[ns] 2kB 2020-03-01T04:00:00 ... 20...
  * latitude             (latitude) float32 1kB -89.72 -89.17 ... 89.17 89.72
  * longitude            (longitude) float32 2kB 0.4167 1.25 ... 358.7 359.6
    pressure             float32 4B ...
Data variables:
    geopotential_height  (realization, time, latitude, longitude) float32 1GB ...
    latitude_longitude   int32 4B ...
Attributes:
    notes:        removing coords forecast_period and forecast_reference_time
    source:       Data from Met Office Unified Model
    um_version:   13.0
    Conventions:  CF-1.7

In [12]:
ds_good.time -1

<xarray.DataArray 'time' (time: 240)> Size: 2kB
array(['2020-03-01T03:59:59.999999999', '2020-03-01T04:59:59.999999999',
       '2020-03-01T05:59:59.999999999', '2020-03-01T06:59:59.999999999',
       '2020-03-01T07:59:59.999999999', '2020-03-01T08:59:59.999999999',
       '2020-03-01T09:59:59.999999999', '2020-03-01T10:59:59.999999999',
       '2020-03-01T11:59:59.999999999', '2020-03-01T12:59:59.999999999',
       '2020-03-01T13:59:59.999999999', '2020-03-01T14:59:59.999999999',
       '2020-03-01T15:59:59.999999999', '2020-03-01T16:59:59.999999999',
       '2020-03-01T17:59:59.999999999', '2020-03-01T18:59:59.999999999',
       '2020-03-01T19:59:59.999999999', '2020-03-01T20:59:59.999999999',
       '2020-03-01T21:59:59.999999999', '2020-03-01T22:59:59.999999999',
       '2020-03-01T23:59:59.999999999', '2020-03-02T00:59:59.999999999',
       '2020-03-02T01:59:59.999999999', '2020-03-02T02:59:59.999999999',
       '2020-03-02T03:59:59.999999999', '2020-03-02T04:59:59.999999999',
       '2020-03-02T05:59:59.999999999', '2020-03-02T06:59:59.999999999',
       '2020-03-02T07:59:59.999999999', '2020-03-02T08:59:59.999999999',
       '2020-03-02T09:59:59.999999999', '2020-03-02T10:59:59.999999999',
       '2020-03-02T11:59:59.999999999', '2020-03-02T12:59:59.999999999',
       '2020-03-02T13:59:59.999999999', '2020-03-02T14:59:59.999999999',
       '2020-03-02T15:59:59.999999999', '2020-03-02T16:59:59.999999999',
       '2020-03-02T17:59:59.999999999', '2020-03-02T18:59:59.999999999',
...
       '2020-03-09T13:59:59.999999999', '2020-03-09T14:59:59.999999999',
       '2020-03-09T15:59:59.999999999', '2020-03-09T16:59:59.999999999',
       '2020-03-09T17:59:59.999999999', '2020-03-09T18:59:59.999999999',
       '2020-03-09T19:59:59.999999999', '2020-03-09T20:59:59.999999999',
       '2020-03-09T21:59:59.999999999', '2020-03-09T22:59:59.999999999',
       '2020-03-09T23:59:59.999999999', '2020-03-10T00:59:59.999999999',
       '2020-03-10T01:59:59.999999999', '2020-03-10T02:59:59.999999999',
       '2020-03-10T03:59:59.999999999', '2020-03-10T04:59:59.999999999',
       '2020-03-10T05:59:59.999999999', '2020-03-10T06:59:59.999999999',
       '2020-03-10T07:59:59.999999999', '2020-03-10T08:59:59.999999999',
       '2020-03-10T09:59:59.999999999', '2020-03-10T10:59:59.999999999',
       '2020-03-10T11:59:59.999999999', '2020-03-10T12:59:59.999999999',
       '2020-03-10T13:59:59.999999999', '2020-03-10T14:59:59.999999999',
       '2020-03-10T15:59:59.999999999', '2020-03-10T16:59:59.999999999',
       '2020-03-10T17:59:59.999999999', '2020-03-10T18:59:59.999999999',
       '2020-03-10T19:59:59.999999999', '2020-03-10T20:59:59.999999999',
       '2020-03-10T21:59:59.999999999', '2020-03-10T22:59:59.999999999',
       '2020-03-10T23:59:59.999999999', '2020-03-11T00:59:59.999999999',
       '2020-03-11T01:59:59.999999999', '2020-03-11T02:59:59.999999999'],
      dtype='datetime64[ns]')
Coordinates:
  * time      (time) datetime64[ns] 2kB 2020-03-01T04:00:00 ... 2020-03-11T03...
    pressure  float32 4B ...

In [13]:
import numpy as np

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [15]:
ds_fixed = ds_good.copy(deep=True)

In [16]:
ds_fixed.time.values[:] = np.arange(np.datetime64('2020-04-01T04:00:00'), np.datetime64('2020-04-11T04:00:00'), np.timedelta64(1, 'h'), dtype='datetime64[ns]')

In [17]:
ds_fixed.geopotential_height.values = ds_bad.geopotential_height.values

In [18]:
ds_fixed.to_netcdf('/gws/nopw/j04/mcs_prime/mmuetz/data/UM_sims/u-di728/share/cycle/20200401T0000Z/engl/um/englaa_pb.merged.20200401T0000Z.u-di728.m01s16i202.500hPa.fixed.nc')

In [19]:
ds_bad.latitude.values[[0, -1]]

array([-89.72222,  89.72224], dtype=float32)

In [20]:
for m in range(1, 13):
    ds = xr.open_dataset(f'/gws/nopw/j04/mcs_prime/mmuetz/data/UM_sims/u-di728/share/cycle/2020{m:02d}01T0000Z/engl/um/englaa_pb.merged.2020{m:02d}01T0000Z.u-di728.m01s16i202.500hPa.nc')
    print(m, ds.latitude.values[[0, -1]])

1 [-89.72222  89.72224]
2 [-89.72222  89.72224]
3 [-89.72222  89.72224]
4 [-89.72222  89.72224]
5 [-89.72222  89.72224]
6 [-89.72222  89.72224]
7 [-89.72222  89.72224]
8 [-89.72222  89.72224]
9 [-89.72222  89.72224]
10 [-89.72222  89.72224]
11 [-89.72222  89.72224]
12 [-89.72222  89.72224]


In [21]:
for m in range(1, 13):
    ds = xr.open_dataset(f'/gws/nopw/j04/mcs_prime/mmuetz/data/UM_sims/u-dg135/share/cycle/2020{m:02d}01T0000Z/engl/um/englaa_pb.merged.2020{m:02d}01T0000Z.u-dg135.m01s16i202.500hPa.nc')
    print(m, ds.latitude.values[[0, -1]])

1 [-89.72222  89.72224]
2 [-89.72222  89.72224]
3 [-89.72222  89.72224]
4 [-89.72222  89.72224]
5 [-89.72222  89.72224]
6 [-89.72222  89.72224]
7 [-89.72222  89.72224]
8 [-89.72222  89.72224]
9 [-89.72222  89.72224]
10 [-89.72222  89.72224]
11 [-89.72222  89.72224]
12 [-89.72222  89.72224]


In [22]:
for m in range(1, 13):
    ds = xr.open_dataset(f'/gws/nopw/j04/mcs_prime/mmuetz/data/UM_sims/u-di727/share/cycle/2020{m:02d}01T0000Z/engl/um/englaa_pb.merged.2020{m:02d}01T0000Z.u-di727.m01s16i202.500hPa.nc')
    print(m, ds.latitude.values[[0, -1]])

1 [-89.72222  89.72224]
2 [-89.72222  89.72224]
3 [-89.72222  89.72224]
4 [-89.72222  89.72224]
5 [-89.72222  89.72224]
6 [-89.72222  89.72224]
7 [-89.72222  89.72224]
8 [-89.72222  89.72224]
9 [-89.72222  89.72224]
10 [-89.72222  89.72224]
11 [-89.72222  89.72224]
12 [-89.72222  89.72224]
